Repository s-tip/stip-sns, pull requests merged in 2020-09, with the labels that each got.

#78 Fixed an issue about a loading animation and remove an unused function and library.
  src/daemon/slack/receive.py
  src/feeds/static/js/feeds.js
  src/feeds/views.py
Labels: bug

#79 version 1.0.1 -> 1.1
  version
Labels: enhancement

#81 Fix to collaborate with Slack
  src/daemon/slack/receive.py
  src/settings.py
Labels: bug

#84 Fix to specify the timezone in the .env file.
  src/settings.py
Labels: bug

#85 Release Candidate for S-TIP Version 1.1
  src/activities/views.py
  src/core/forms.py
  src/core/static/css/password.css
  src/core/static/js/stip_ajax.js
  src/core/templates/core/_cover.html
  src/core/templates/core/password.html
  src/core/templates/core/profile.html
  src/core/views.py
  src/daemon/slack/receive.py
  src/decorators.py
  src/feeds/feed_stix2.py
  src/feeds/static/js/feeds.js
  src/feeds/templates/feeds/feeds.html
  src/feeds/views.py
  src/locale/en/LC_MESSAGES/djangojs.mo
  src/locale/ja/LC_MESSAGES/django.mo
  src/locale/ja/LC_MESSAGES/django.po
  src/locale/ja/LC_MESSAGES/djangojs.mo
  src/messenger/views.py
  src/search/static/js/search.js
  src/search/templates/search/search.html
  src/settings.py
  src/urls.py
  version
Labels: bug, enhancement
